#!/bin/bash
set -xe

lerna publish from-package --registry=$NPM_RELEASE_REGISTRY
# lerna exec --ignore=@dws/muster-playground --ignore=@dws/muster-website -- npm publish --registry=$NPM_RELEASE_REGISTRY
