#!/bin/bash
COMMAND=$1
if [ -z "$COMMAND" ]; then
  echo "No pre-push command specified"
  exit 1
fi

NAME=$(git branch | grep '*' | sed 's/* //')

if [ -z "$NAME" ]; then
	NAME='(empty branch)'
fi

# Don't run on rebase
if [ "$NAME" = "(no branch)" ]; then
	exit 0
fi

echo "Running pre-push hook on $NAME"

CHANGES=$(git diff --numstat | wc -l)
CACHED_CHANGES=$(git diff --cached --numstat | wc -l)
UNTRACKED_FILES=$(git status --porcelain | grep '^??' | wc -l)
TOTAL_CHANGES=$(($CHANGES + $CACHED_CHANGES + $UNTRACKED_FILES))

if [ $TOTAL_CHANGES -ne "0" ]
then
  echo "Stashing changes..."
  git stash save -k -u
  echo "Changes stashed"
  trap "{ code=\$?; echo \"Restoring stash...\"; git stash pop -q; echo \"Stash restored\"; exit \$code; }" EXIT
fi

$COMMAND

RETVAL=$?

if [ $RETVAL -ne 0 ]; then
  echo "Pre-push hook failed"
  exit $RETVAL
else
  echo "Pre-push hook succeeded"
  exit 0
fi
